# Generated by Django 5.0 on 2023-12-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40, verbose_name='Название товара: ')),
                ('product_categori', models.CharField(max_length=40, verbose_name='Категория товара: ')),
                ('product_description', models.CharField(max_length=400, verbose_name='Описание товара: ')),
            ],
        ),
    ]
